### ISSUE TITLE
invalid link in readme

### ISSUE THREAD

**Issue by maybeec** [mojohaus/servicedocgen-maven-plugin#13] opened 2015-11-04 18:48 UTC
There is a link in the readme to http://www.mojohaus.org/servicedocgen-maven-plugin/ which does not point to a valid mojohaus page.

**Comment by jochenw** [comment] 2015-11-05 06:42
Well, but the solution seems to be to publish docs, rather than fixing the link.
@hohwille: Could you act on that, please?

**Comment by hohwille** [comment] 2015-11-05 07:37
@may-bee the link is correct but the site could not yet be published due to technical problems.
@jochenw I do not understand your comment in this context. Maybe you got the wrong github repository..

**Comment by hohwille** [comment] 2015-11-05 07:39
Duplicate of #5 - closing.

**Closed as completed by hohwille** 2015-11-05 07:39 UTC
